[versions]
agp = "8.11.1"
atomicfu = "0.29.0"
coreKtx = "1.16.0"
kotestAssertionsCore = "5.9.1"
kotlin = "2.2.0"
kotlinxCoroutinesCore = "1.10.2"
android-minSdk = "24"
android-compileSdk = "36"
kotlinxCoroutinesTest = "1.10.2"
lifecycleViewmodelKtx = "2.9.2"

[libraries]
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotestAssertionsCore" }
kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }

[plugins]
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.29.0" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
